language: node_js
node_js:
  - "4"
sudo: false
cache:
  directories:
  - $HOME/calibre-bin
  - node_modules
before_script:
  - mkdir -p $HOME/calibre-bin/calibre
  - export PATH=$PATH:$HOME/calibre-bin/calibre
  - >
    which calibre ||
    wget -nv -O- https://raw.githubusercontent.com/kovidgoyal/calibre/master/setup/linux-installer.py |
    python -c "import sys; main=lambda x,y:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main('~/calibre-bin', True)"
script:
  - npm run archive
notifications:
  email:
    on_success: never
    on_failure: never
